[project]
name = "mustapha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aerich>=0.9.2",
    "fastapi>=0.136.3",
    "pydantic[email]>=2.13.4",
    "python-dotenv>=1.2.2",
    "tortoise-orm[asyncpg]>=0.25.4",
    "uvicorn[standard]>=0.48.0",
]
